# Use an official Python runtime as a parent image
FROM python:3.11

# Set the working directory in the container
# WORKDIR /usr/src/app

# Install any needed packages specified in requirements.txt
RUN apt install python3-louis libcairo2-dev pkg-config python3-dev

# Define environment variable
# ENV NAME World

# Run the application
# CMD ["python", "./your-script.py"]
